module.exports.invalidBody = (key) => `${key} is invalid`;
module.exports.incompleteKey = (key) => `Missing required key: ${key}`;
module.exports.incompleteValue = (key) => `Missing require value: ${key}`;
module.exports.invalidEmailOrPassword = () => 'Invalid Email or Password';
module.exports.invalidType = (key) => `Value is invalid data type: ${key}`;
module.exports.notFoundResource = (key) => `Resource not found: ${key}`;
module.exports.errorFindResource = (key) => `Failed find resource: ${key}`;
module.exports.errorCreateResource = (key) => `Failed create resource:${key} `;
module.exports.errorUpdateResource = (key) => `Failed update resource:${key} `;
module.exports.errorDeleteResource = (key) => `Failed delete resource: ${key}`;
module.exports.invalidFormat = (key) => `invalid format: ${key}`;
module.exports.alreadyUsed = (key) => `invalid format: ${key}`;
module.exports.invalidOption = (key) => `Value is outside option ${key}`;
module.exports.loginError = () => 'Failed to login';
module.exports.unauthorized = () => 'Failed to unauthorized';
module.exports.expired = (key) => `${key} has expired`;
module.exports.invalidMaxLength = (key, value) => `Length of ${key} shall not be more than ${value}`;
module.exports.invalidMinLength = (key, value) => `Length of ${key} shall not be less than ${value}`;
module.exports.invalidMaxValue = (key, value) => `Value of ${key} shall not be more than ${value}`;
module.exports.invalidMinValue = (key, value) => `Value of ${key} shall not be less than ${value}`;
